//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Books = new HashSet<Books>();
            this.Complaints = new HashSet<Complaints>();
            this.Reviews = new HashSet<Reviews>();
            this.RoleRequests = new HashSet<RoleRequests>();
            this.UnfreezeRequests = new HashSet<UnfreezeRequests>();
            this.UserBooks = new HashSet<UserBooks>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public int RoleID { get; set; }
        public bool IsFrozen { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<RoleRequests> RoleRequests { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual ICollection<UserBooks> UserBooks { get; set; }
    }
}
